Name:           ros-jade-opencv-apps
Version:        1.11.12
Release:        0%{?dist}
Summary:        ROS opencv_apps package

Group:          Development/Libraries
License:        BSD
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-jade-cv-bridge
Requires:       ros-jade-dynamic-reconfigure
Requires:       ros-jade-image-transport
Requires:       ros-jade-message-runtime
Requires:       ros-jade-nodelet
Requires:       ros-jade-roscpp
Requires:       ros-jade-std-srvs
BuildRequires:  ros-jade-catkin
BuildRequires:  ros-jade-cv-bridge
BuildRequires:  ros-jade-dynamic-reconfigure
BuildRequires:  ros-jade-image-proc
BuildRequires:  ros-jade-image-transport
BuildRequires:  ros-jade-image-view
BuildRequires:  ros-jade-message-generation
BuildRequires:  ros-jade-nodelet
BuildRequires:  ros-jade-rosbag
BuildRequires:  ros-jade-roscpp
BuildRequires:  ros-jade-rosservice
BuildRequires:  ros-jade-rostest
BuildRequires:  ros-jade-rostopic
BuildRequires:  ros-jade-std-srvs
BuildRequires:  ros-jade-topic-tools

%description
The opencv_apps package, most of code is taken from
https://github.com/Itseez/opencv/tree/master/samples/cpp

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jade/setup.sh" ]; then . "/opt/ros/jade/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/jade" \
        -DCMAKE_PREFIX_PATH="/opt/ros/jade" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jade/setup.sh" ]; then . "/opt/ros/jade/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/jade

%changelog
* Thu Mar 10 2016 Kei Okada <kei.okada@gmail.com> - 1.11.12-0
- Autogenerated by Bloom

* Sun Jan 31 2016 Kei Okada <kei.okada@gmail.com> - 1.11.11-0
- Autogenerated by Bloom

* Sat Jan 16 2016 Kei Okada <kei.okada@gmail.com> - 1.11.10-0
- Autogenerated by Bloom

* Sun Nov 29 2015 Kei Okada <kei.okada@gmail.com> - 1.11.9-0
- Autogenerated by Bloom

* Wed Jul 15 2015 Kei Okada <kei.okada@gmail.com> - 1.11.8-0
- Autogenerated by Bloom

